#暴露所有
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: account-auth-service
          uri: lb://account-auth-service
          predicates:
            - Path=/oauth/**
        - id: message-socket-hash
          uri: socket://message-netty-service
          predicates:
            - Path=/message/websocket/**
        - id: message-netty-service
          uri: lb://message-netty-service
          predicates:
            - Path=/message/connection
        - id: message-static
          uri: lb://message-netty-service
          predicates:
            - Path=/message/socketIo-client
          filters:
            - StripPrefix=1
gateway:
  dynamicRoute:
    enabled: true
    type: nacos

