server:
  port: 9527

#spring cloud alibaba nacos config
spring:
  cloud:
    nacos:
      config:
        server-addr: 120.76.65.160:8848
        file-extension: yaml
        namespace: 9cd8de3b-030a-49f1-9256-f04de35cdb9e
        group: DEV_GROUP
        extension-configs[0]:
          data-id: rabbitmq-config.yaml
          group: DEV_GROUP
          refresh: true
      discovery:
        server-addr: 120.76.65.160:8848

#当前项目运行环境 EnvironmentConfig类使用.
env:
  dev
#RPC注册直连服务配置key
direct:
  nodesMap: "{cloud-gateway: '172.0.0.1:8080'}"

