nacos:
  server-addr: ${NACOS_HOST:nacos-cloud.hongqy1024.cn}:${NACOS_PORT:8848}
  group: ${NACOS_GROUP:TEST_GROUP}
  namespace: ${NACOS_NAMESPACE:e3f4bf0e-5118-4e06-90de-087cb676b98c}

spring:
  config:
    import:
      - optional:nacos:redis-config.yaml
      - optional:nacos:db-app-config.yaml
  cloud:
    nacos:
      config:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        group: ${nacos.group}
        file-extension: yaml
      discovery:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        group: ${nacos.group}