nacos:
  server-addr: ${NACOS_HOST:hongqy1024.cn:8848}:${NACOS_PORT:8848}
  group: ${NACOS_GROUP:DEV_GROUP}
  namespace: ${NACOS_NAMESPACE:9cd8de3b-030a-49f1-9256-f04de35cdb9e}

#开发环境
spring:
  config:
    import:
      - optional:nacos:redis-config.yaml
      - optional:nacos:db-app-config.yaml
  cloud:
    nacos:
      config:
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        group: ${nacos.group}
        file-extension: yaml
      discovery:
        ephemeral: false # false为永久实例，true表示临时实例
        server-addr: ${nacos.server-addr}
        namespace: ${nacos.namespace}
        group: ${nacos.group}