server:
  port: 8083
spring:
  application:
    name: cloud-consumer-demo
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true。
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:10010/eureka
  instance:
    #实例id名称
    instance-id: consumer-demo-8083
    #访问路径可以显示IP地址
    prefer-ip-address: true