server:
  port: 8001
spring:
  application:
    name: cloud-provider-demo
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true。
    fetchRegistry: true  #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:10010/eureka
  instance:
    instance-id: provider-demo-8001 #实例id名称
    prefer-ip-address: true #访问路径可以显示IP地址
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.hqy    # 所有Entity别名类所在包
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers: com.hqy.dao.base.BaseDao
  not-empty: false
  identity: mysql
management:
  endpoints:
    web:
      exposure:
        include: "*"