server:
  port: 8081
spring:
  application:
    name: cloud-provider-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
eureka:
  client:
    register-with-eureka: true #表示是否将自己注册进EurekaServer默认为true。
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:10010/eureka
  instance:
    #实例id名称
    instance-id: provider-demo-8081
    #访问路径可以显示IP地址
    prefer-ip-address: true
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.hqy    # 所有Entity别名类所在包
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers: com.hqy.dao.base.BaseDao
  not-empty: false
  identity: mysql