env:
  dev
spring:
  application:
    name: public-basic-service
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.hqy.basic.entity    # 所有Entity别名类所在包
  configuration:
    map-underscore-to-camel-case: true