mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

management: #暴露所有
  endpoints:
    web:
      exposure:
        include: "*"
encrypt:
  key-store:
    password: hongqy@2021
    alias: jwt
    secret: hongqy@2021
    location: classpath:jwt.jks
