server:
  port: 8010
spring:
  application:
    name: alibaba-provider-demo
  cloud:
    nacos: #注册中心改用nacos
      discovery:
        server-addr: localhost:8848 #配置nacos地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://120.76.65.160:3306/hqy?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hongqy@2021
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.hqy    # 所有Entity别名类所在包
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers: com.hqy.dao.base.BaseDao
  not-empty: false
  identity: mysql
management: #暴露所有
  endpoints:
    web:
      exposure:
        include: "*"