spring:
  application:
    name: cloud-provider-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://120.76.65.160:3306/hqy?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hongqy@2021
